In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("../05_Epic2_Data_Collection_Analysis/Crop_Recommendation.csv")

df.head()

    N   P   K  temperature   humidity        ph    rainfall label
0  90  42  43    20.879744  82.002744  6.502985  202.935536  rice
1  85  58  41    21.770462  80.319644  7.038096  226.655537  rice
2  60  55  44    23.004459  82.320763  7.840207  263.964248  rice
3  74  35  40    26.491096  80.158363  6.980401  242.864034  rice
4  78  42  42    20.130175  81.604873  7.628473  262.717340  rice

In [5]:
df.shape

(2200, 8)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   N            2200 non-null   int64
 1   P            2200 non-null   int64
 2   K            2200 non-null   int64
 3   temperature  2200 non-null   float64
 4   humidity     2200 non-null   float64
 5   ph           2200 non-null   float64
 6   rainfall     2200 non-null   float64
 7   label        2200 non-null   str
dtypes: float64(4), int64(3), str(1)
memory usage: 137.6 KB

In [7]:
df.isnull().sum()

N              0
P              0
K              0
temperature    0
humidity       0
ph             0
rainfall       0
label          0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df = df.drop_duplicates()

In [10]:
df.dtypes

N                int64
P                int64
K                int64
temperature    float64
humidity       float64
ph             float64
rainfall       float64
label              str
dtype: object

In [12]:
%pip install scikit-learn

Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in c:\Users\charan sai molabanti\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.5.0)
Collecting scipy>=1.10.0 (from scikit-learn)
  Downloading scipy-1.18.0-cp313-cp313-win_amd64.whl.metadata (61 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Downloading joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Downloading threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   -- ------------------------------------- 0.5/8.2 MB 208.6 kB/s eta 0:00:37
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   --- ------------------------------------ 0.8/8.2 MB 119.2 kB/s eta 0:01:03
   ----- ---------------------------------- 1.0/8.2 MB 50.3 kB/s eta 0:02:22
   ----- ---------------------------------- 1.0/8.2 MB 50.3 kB/s eta 0:02:22
   ----- ---------------------------------- 1.0/8.2 MB 50.3 kB/s eta 0:02:22
   ------ --------------------------------- 1.3/8.2 MB 64.2 kB/s eta 0:01:48
   ------ --------------------------------- 1.3/8.2 MB 64.2 kB/s eta 0:01:48
   ------ --------------------------------- 1.3/8.2 MB 64.2 kB/s eta 0:01:48
   ------- -------------------------------- 1.6/8.2 MB 77.3 kB/s eta 0:01:26
   ------- -------------------------------- 1.6/8.2 MB 77.3 kB/s eta 0:01:26
   -------- ------------------------------- 1.8/8.2 MB 90.1 kB/s eta 0:01:11
   -------- ------------------------------- 1.8/8.2 MB 90.1 kB/s eta 0:01:11
   -------- ------------------------------- 1.8/8.2 MB 90.1 kB/s eta 0:01:11
   ---------- ----------------------------- 2.1/8.2 MB 101.4 kB/s eta 0:01:01
   ---------- ----------------------------- 2.1/8.2 MB 101.4 kB/s eta 0:01:01
   ---------- ----------------------------- 2.1/8.2 MB 101.4 kB/s eta 0:01:01
   ---------- ----------------------------- 2.1/8.2 MB 101.4 kB/s eta 0:01:01
   ---------- ----------------------------- 2.1/8.2 MB 101.4 kB/s eta 0:01:01
   ---------- ----------------------------- 2.1/8.2 MB 101.4 kB/s eta 0:01:01
   ---------- ----------------------------- 2.1/8.2 MB 101.4 kB/s eta 0:01:01
   ---------- ----------------------------- 2.1/8.2 MB 101.4 kB/s eta 0:01:01
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ----------- ---------------------------- 2.4/8.2 MB 106.0 kB/s eta 0:00:55
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   ------------ --------------------------- 2.6/8.2 MB 99.4 kB/s eta 0:00:56
   -------------- ------------------------- 2.9/8.2 MB 96.0 kB/s eta 0:00:56
   -------------- ------------------------- 2.9/8.2 MB 96.0 kB/s eta 0:00:56
   -------------- ------------------------- 2.9/8.2 MB 96.0 kB/s eta 0:00:56
   -------------- ------------------------- 2.9/8.2 MB 96.0 kB/s eta 0:00:56
   -------------- ------------------------- 2.9/8.2 MB 96.0 kB/s eta 0:00:56
   -------------- ------------------------- 2.9/8.2 MB 96.0 kB/s eta 0:00:56
   -------------- ------------------------- 2.9/8.2 MB 96.0 kB/s eta 0:00:56
   -------------- ------------------------- 2.9/8.2 MB 96.0 kB/s eta 0:00:56
   --------------- ------------------------ 3.1/8.2 MB 99.6 kB/s eta 0:00:51
   --------------- ------------------------ 3.1/8.2 MB 99.6 kB/s eta 0:00:51
   --------------- ------------------------ 3.1/8.2 MB 99.6 kB/s eta 0:00:51
   ---------------- ----------------------- 3.4/8.2 MB 106.4 kB/s eta 0:00:45
   ---------------- ----------------------- 3.4/8.2 MB 106.4 kB/s eta 0:00:45
   ---------------- ----------------------- 3.4/8.2 MB 106.4 kB/s eta 0:00:45
   ---------------- ----------------------- 3.4/8.2 MB 106.4 kB/s eta 0:00:45
   ----------------- ---------------------- 3.7/8.2 MB 107.8 kB/s eta 0:00:42
   ----------------- ---------------------- 3.7/8.2 MB 107.8 kB/s eta 0:00:42
   ----------------- ---------------------- 3.7/8.2 MB 107.8 kB/s eta 0:00:42
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   ------------------- -------------------- 3.9/8.2 MB 114.1 kB/s eta 0:00:38
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   -------------------- ------------------- 4.2/8.2 MB 114.5 kB/s eta 0:00:35
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   --------------------- ------------------ 4.5/8.2 MB 155.0 kB/s eta 0:00:25
   ----------------------- ---------------- 4.7/8.2 MB 137.3 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.2 MB 137.3 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.2 MB 137.3 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.2 MB 137.3 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.2 MB 137.3 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.2 MB 137.3 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.2 MB 137.3 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.2 MB 137.3 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.2 MB 137.3 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.2 MB 137.3 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.2 MB 137.3 kB/s eta 0:00:26
   ----------------------- ---------------- 4.7/8.2 MB 137.3 kB/s eta 0:00:26
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------ --------------- 5.0/8.2 MB 133.8 kB/s eta 0:00:24
   ------------------------- -------------- 5.2/8.2 MB 106.4 kB/s eta 0:00:28
   ------------------------- -------------- 5.2/8.2 MB 106.4 kB/s eta 0:00:28
   ------------------------- -------------- 5.2/8.2 MB 106.4 kB/s eta 0:00:28
   ------------------------- -------------- 5.2/8.2 MB 106.4 kB/s eta 0:00:28
   ------------------------- -------------- 5.2/8.2 MB 106.4 kB/s eta 0:00:28
   ------------------------- -------------- 5.2/8.2 MB 106.4 kB/s eta 0:00:28
   -------------------------- ------------- 5.5/8.2 MB 107.4 kB/s eta 0:00:25
   -------------------------- ------------- 5.5/8.2 MB 107.4 kB/s eta 0:00:25
   -------------------------- ------------- 5.5/8.2 MB 107.4 kB/s eta 0:00:25
   -------------------------- ------------- 5.5/8.2 MB 107.4 kB/s eta 0:00:25
   -------------------------- ------------- 5.5/8.2 MB 107.4 kB/s eta 0:00:25
   -------------------------- ------------- 5.5/8.2 MB 107.4 kB/s eta 0:00:25
   -------------------------- ------------- 5.5/8.2 MB 107.4 kB/s eta 0:00:25
   ---------------------------- ----------- 5.8/8.2 MB 117.2 kB/s eta 0:00:21
   ---------------------------- ----------- 5.8/8.2 MB 117.2 kB/s eta 0:00:21
   ---------------------------- ----------- 5.8/8.2 MB 117.2 kB/s eta 0:00:21

In [13]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

df["label"] = encoder.fit_transform(df["label"])

df.head()

    N   P   K  temperature   humidity        ph    rainfall  label
0  90  42  43    20.879744  82.002744  6.502985  202.935536     20
1  85  58  41    21.770462  80.319644  7.038096  226.655537     20
2  60  55  44    23.004459  82.320763  7.840207  263.964248     20
3  74  35  40    26.491096  80.158363  6.980401  242.864034     20
4  78  42  42    20.130175  81.604873  7.628473  262.717340     20

In [14]:
X = df.drop("label", axis=1)

y = df["label"]

print(X.head())

print(y.head())

    N   P   K  temperature   humidity        ph    rainfall
0  90  42  43    20.879744  82.002744  6.502985  202.935536
1  85  58  41    21.770462  80.319644  7.038096  226.655537
2  60  55  44    23.004459  82.320763  7.840207  263.964248
3  74  35  40    26.491096  80.158363  6.980401  242.864034
4  78  42  42    20.130175  81.604873  7.628473  262.717340
0    20
1    20
2    20
3    20
4    20
Name: label, dtype: int64

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(1760, 7)
(440, 7)

In [16]:
df.to_csv("Processed_Dataset.csv", index=False)